In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [7]:
# 按cause类型拼接数据
def concat_file(cause_files):
    file1 = '../train/' + str(cause_files[0]) + '.csv'
    data = pd.read_csv(file1)
    data['label'] = cause_files[0]
    for num in cause_files[1:]:
        file = '../train/' + str(num) + '.csv'
        data_me = pd.read_csv(file)
        data_me['label'] = num
        data = data.append(data_me)
    # 删除无关列、全为nan的列
    data.reset_index(drop=True, inplace=True)
    data.drop(columns=['feature3_1', 'feature3_2', 'feature3_3', 
                        'feature3_4', 'feature3_5', 'feature3_6', 
                        'feature3_7', 'feature3_8', 'feature14', 'Date & Time'], 
                        inplace=True)
    data.dropna(axis=1, how='all', inplace=True)

    return data
# 按cause类型拼接数据，考虑大于和小于200
def concat_abnormal_file(cause_files):
    file1 = '../train/' + str(cause_files[0]) + '.csv'
    data = pd.read_csv(file1)
    data['label'] = cause_files[0]
    data = data[data['feature0'] < 200]
    for num in cause_files[1:]:
        file = '../train/' + str(num) + '.csv'
        data_me = pd.read_csv(file)
        data_me['label'] = num
        data_me = data_me[data_me['feature0'] < 200]
        data = data.append(data_me)
    # 删除无关列、全为nan的列
    data.reset_index(drop=True, inplace=True)
    data.drop(columns=['feature3_1', 'feature3_2', 'feature3_3', 
                        'feature3_4', 'feature3_5', 'feature3_6', 
                        'feature3_7', 'feature3_8', 'feature14', 'Date & Time'], 
                        inplace=True)
    data.dropna(axis=1, how='all', inplace=True)

    return data

In [8]:
cause1_nums = np.load('../cause1_nums.npy')
cause2_nums = np.load('../cause2_nums.npy')
cause3_nums = np.load('../cause3_nums.npy')
cause2_3_nums = np.load('../cause2_3_nums.npy')

In [9]:
concat_abnormal_file(cause1_nums)

,feature0,feature1,feature2,feature11,feature12,feature13,feature15,feature16,feature17,feature18,...,feature61_7,feature69_0,feature69_1,feature69_2,feature69_3,feature69_4,feature69_5,feature69_6,feature69_7,label
0,0.08,7.00,1.90,0.00,10.00,1685.0,30.0,11.41,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,915
1,2.42,15.16,3.00,0.00,1.64,12430.0,61.0,12.46,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,915
2,40.91,18.21,3.00,0.00,1.90,115633.0,477.0,12.58,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,915
3,2.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,916
4,4.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,916
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2665,185.21,18.74,3.93,0.00,13.05,98106.0,614.0,13.72,4.0,11.38,...,-1.63,7.63,-1.69,-5.94,1.00,3.56,0.25,2.25,-1.25,2614
2666,149.62,12.47,3.82,0.00,9.53,120456.0,767.0,13.08,4.0,17.38,...,3.44,10.44,14.75,10.75,8.94,8.88,8.63,17.13,9.31,2620
2667,98.90,8.75,3.04,0.00,1.39,7690.0,72.0,14.44,4.0,18.13,...,8.00,13.75,3.31,9.63,6.19,0.56,7.25,3.31,2.69,2725
2668,78.18,12.26,3.57,0.37,1.47,36958.0,275.0,11.64,4.0,16.25,...,5.50,12.06,9.81,16.50,11.81,10.44,6.50,8.25,8.06,2946
2669,157.13,16.77,3.81,2.42,15.54,93369.0,489.0,11.96,4.0,18.25,...,4.75,-4.44,3.88,7.13,7.44,12.69,7.44,18.88,11.75,2946

In [10]:
concat_abnormal_file(cause2_nums)

,feature0,feature1,feature2,feature11,feature12,feature13,feature15,feature16,feature17,feature18,...,feature61_7,feature69_0,feature69_1,feature69_2,feature69_3,feature69_4,feature69_5,feature69_6,feature69_7,label
0,136.26,11.64,2.00,0.0,15.78,314577,1302,10.52,2,3.88,...,-8.06,1.81,2.06,-4.50,6.13,-2.19,-3.38,-17.75,-9.88,1758
1,142.17,10.22,2.00,0.0,16.57,371105,1509,11.28,2,4.13,...,2.00,-3.75,2.94,6.75,-7.06,-11.50,-14.13,-0.94,1.50,1758
2,145.42,8.76,2.00,0.0,10.38,397324,1580,9.32,2,6.25,...,-3.56,-4.06,6.94,-0.19,4.19,-14.69,-15.94,-6.94,-5.56,2035
3,141.44,11.44,2.00,0.0,13.26,369592,1473,3.18,2,6.25,...,-4.63,-4.31,0.81,-3.69,0.44,0.38,4.38,-5.50,-11.56,2078
4,175.54,9.34,2.00,0.0,8.73,396903,1581,2.40,2,8.13,...,-7.19,-1.25,-3.00,-1.19,-4.38,-3.38,7.44,-4.50,-6.44,2079
5,91.70,14.63,1.00,0.0,8.94,393825,1558,11.56,1,-2.00,...,-6.94,-4.81,-1.75,-5.38,-12.19,-10.94,2.94,-7.38,-14.50,2083
6,88.46,8.90,2.00,0.0,11.45,360257,1449,10.44,2,3.63,...,2.94,-8.88,-8.13,-13.00,-12.13,-7.06,-4.31,-6.56,0.75,2227
7,97.80,16.15,1.21,0.0,8.71,375553,1498,9.52,1,10.88,...,13.69,-3.00,4.25,-10.44,3.38,-5.94,1.75,-2.50,12.06,2228

In [11]:
concat_abnormal_file(cause3_nums)

,feature0,feature1,feature2,feature11,feature12,feature13,feature15,feature16,feature17,feature18,...,feature61_7,feature69_0,feature69_1,feature69_2,feature69_3,feature69_4,feature69_5,feature69_6,feature69_7,label
0,188.50,18.23,1.00,0.00,10.50,357248.0,1429.0,9.45,1.0,18.25,...,3.75,-11.38,0.19,-12.19,5.00,-1.00,7.44,8.56,-3.88,670
1,187.30,16.49,1.00,0.00,11.76,395018.0,1582.0,10.06,1.0,12.63,...,8.56,4.50,-17.25,-6.31,-10.50,3.88,-17.69,9.88,7.25,670
2,128.23,11.93,1.00,0.00,9.20,402378.0,1599.0,9.10,1.0,NaN,...,-4.06,-17.81,-3.06,-2.25,15.31,6.44,2.06,-12.50,-1.69,670
3,97.33,9.14,1.00,0.15,12.51,381912.0,1519.0,8.72,1.0,9.13,...,3.13,-12.13,-10.50,-11.38,6.19,-1.69,-9.50,-12.25,-1.38,670
4,32.62,9.12,1.00,2.13,12.25,307940.0,1239.0,9.14,1.0,9.88,...,-10.06,-8.94,3.00,-13.13,-11.69,-14.31,-10.06,5.38,-5.63,670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,63.05,8.94,1.00,0.25,12.29,331924.0,1359.0,3.14,1.0,-11.63,...,-17.69,-14.94,-12.31,-8.50,-6.69,-17.13,-18.19,-6.94,-12.06,2977
4996,59.63,8.72,1.00,0.19,9.58,292926.0,1187.0,4.34,1.0,-9.13,...,-1.56,-13.00,-8.69,-14.00,-5.75,-14.63,-10.94,-14.75,-5.13,2977
4997,154.79,10.20,1.00,0.75,9.56,261885.0,1064.0,5.52,1.0,-13.38,...,-16.69,-12.31,-10.25,-8.69,-3.31,-14.38,-17.75,-8.81,-18.19,2977
4998,176.70,17.36,1.12,0.00,10.69,336972.0,1590.0,9.96,1.0,7.75,...,-5.88,-4.38,0.19,-9.25,-3.81,-8.38,4.81,-0.19,-5.13,2983
4999,150.33,16.21,1.00,0.00,9.94,328319.0,1601.0,9.46,1.0,2.00,...,-8.13,-12.81,-1.69,2.38,-5.13,-5.19,5.13,-3.63,-5.88,2983

In [12]:
concat_abnormal_file(cause2_3_nums)

,feature0,feature1,feature2,feature11,feature12,feature13,feature15,feature16,feature17,feature18,...,feature61_7,feature69_0,feature69_1,feature69_2,feature69_3,feature69_4,feature69_5,feature69_6,feature69_7,label
0,168.75,12.55,1.37,0.07,8.84,392881.0,1590.0,6.76,1.0,-5.00,...,-10.56,-9.81,-8.94,-11.00,-5.19,-8.94,-5.69,-6.81,-4.13,843
1,127.91,11.10,1.20,0.07,9.14,394118.0,1600.0,5.44,1.0,-6.88,...,-14.69,-8.38,-9.19,-12.31,-7.75,-12.38,-8.75,-7.88,-11.19,843
2,147.33,10.66,1.61,0.21,11.69,390368.0,1586.0,6.10,2.0,-12.63,...,-8.56,-12.06,-6.31,-13.25,-13.94,-9.00,-10.13,-7.69,-6.56,843
3,176.94,9.08,1.98,0.63,9.44,391099.0,1585.0,6.36,2.0,-11.50,...,-17.31,-7.38,-10.13,-16.38,-8.25,-12.75,-8.13,-16.56,-14.94,843
4,142.23,8.37,1.98,0.94,10.19,386326.0,1574.0,6.34,2.0,-10.88,...,-7.31,-10.13,-11.50,-10.69,-12.25,-12.25,-9.75,-6.25,-4.31,843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,80.80,17.99,1.00,0.00,9.96,258698.0,1077.0,7.78,1.0,-2.75,...,NaN,-12.50,-12.63,-7.31,-13.75,NaN,NaN,NaN,NaN,2852
988,110.08,16.71,1.00,0.00,9.91,380499.0,1474.0,9.28,1.0,-7.63,...,NaN,-7.31,-6.38,-7.81,-17.56,NaN,NaN,NaN,NaN,2852
989,107.42,16.38,1.00,0.00,8.92,364838.0,1443.0,9.34,1.0,-3.50,...,NaN,9.19,-3.94,-6.13,-12.00,NaN,NaN,NaN,NaN,2852
990,100.49,15.53,1.00,0.00,8.99,380226.0,1471.0,9.66,1.0,-8.50,...,NaN,-11.13,-8.94,-7.50,-13.94,NaN,NaN,NaN,NaN,2852
991,73.73,13.34,1.00,0.00,8.76,362253.0,1405.0,8.12,1.0,-7.75,...,NaN,-11.19,-9.38,-7.75,-10.94,NaN,NaN,NaN,NaN,2852